name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  wait:
    name: Wait for tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: Lint
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  deploy:
    runs-on: ubuntu-latest
    needs:
      - wait

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    # See the following link for documentation:
    # https://github.com/marketplace/actions/dokku
    - name: Push to medusa
      uses: dokku/github-action@v1.4.0
      with:
        ssh_private_key: ${{ secrets.MEDUSA_GLOBAL_DEPLOY_KEY }}
        git_remote_url: ssh://dokku@medusa.datasektionen.se/bea
        # force might feel risky, but there is no good reason why the server
        # should ever not be a mirror of the deploy branch. And the errors we
        # could get otherwise would probably be nasty to deal with
        git_push_flags: --force
